name: generate

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["resources/**"]
  pull_request:
    paths: ["resources/**"]

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: nekowinston/setup-deno@v2.0.0
        with:
          deno-json-path: resources/deno.json
          deno-lock-path: resources/deno.lock
          directory: resources
      - name: Generate Data
        working-directory: resources
        run: deno task generate
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        # only push once upstreamed
        if: ${{ github.repository == 'catppuccin/catppuccin' && github.ref == 'refs/heads/main' }}
        with:
          commit_message: "chore: re-generate data"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
